[package]
name = "lsdk_cli"
version = "1.0.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3" # https://crates.io/crates/color-eyre
crossterm = "0.29.0" # https://crates.io/crates/crossterm
ratatui = "0.29.0"   # https://crates.io/crates/ratatui
